### ISSUE TITLE
Sorting by Percent FC vs. 100%

### ISSUE THREAD

**Issue by hababa2** [jpetersen5/DMBot#5]
When sorting by percent, FCs and overhit 100%s have the same weight, so they can be mixed.
![Screenshot 2024-09-11 184745](https://github.com/user-attachments/assets/8122285f-46bb-4d59-b695-126702848fc6)

**Comment by jpetersen5** [comment]
It should rank by score no matter the % unless the 100%s and FCs are the same exact score, which I think would be an extreme edge case. I don't know what the scores are in this screenshot

**Comment by jpetersen5** [comment]
Oh ok sorting by % yeah I can fix that

**Comment by jpetersen5** [comment]
Fixed in an upcoming release
